### ISSUE TITLE
Question: Why the dependency on java?

### ISSUE THREAD

**Issue by pietrop** [zevaverbach/tpro#14]
Hello, 
This seems like a great and much needed initiative, I was wondering why the dependency on java?

---

For context, we've been working on an open source transcript editor [`@bbc/react-transcript-editor`]( https://github.com/bbc/react-transcript-editor) (see [demo](https://bbc.github.io/react-transcript-editor/) click `load demo`) which has converters for various STT services (including Speechmatics, Gentle, etc..) into the draftJs json data structure. 

And this could potentially be a good approach to simplify the scaling to new providers etc..

**Comment by zevaverbach** [comment]
@pietrop really cool project, thanks for pointing it out!  The only reason for Java here is to use [the Stanford NER](https://nlp.stanford.edu/software/CRF-NER.shtml), which itself is only needed for deciding whether a word is a proper noun.  Do you have any suggestions for a different approach?

**Comment by zevaverbach** [comment]
answering my own question here: #16 will eliminate the Java dependency
